# Generated by Django 4.2.1 on 2024-10-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Course",
            new_name="Items",
        ),
    ]
