# Generated by Django 4.2.1 on 2024-10-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_course_items"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="items",
            options={"verbose_name": "Item", "verbose_name_plural": "Items"},
        ),
    ]
